# Generated by Django 3.2.3 on 2021-07-09 15:31

import contracts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='files/', validators=[contracts.models.Contract.validate_file_extension])),
                ('name', models.TextField(max_length=200)),
                ('text', models.TextField(max_length=1000)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
