# Generated by Django 3.2.5 on 2021-09-06 18:49

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_question_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='text',
        ),
        migrations.AddField(
            model_name='contract',
            name='scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(default='output.pdf', max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pdf',
            field=models.FileField(upload_to='', validators=[contracts.models.Contract.validate_file_extension]),
        ),
    ]
